version: 2

sources:
  - name: staging
    description: Dados vindos do source, com pequenos tratamentos..


    tables:
      - name: stg_base_dados
        description: Tabela com os registros das vendas.
        
      - name: stg_custos_mensais
        description: Tabela com os registros dos custos.

      - name: stg_cadastro_veiculos
        description: Tabela com o cadastro dos veículos da empresa. 

      - name: stg_motivos_ocorrencias
        description: Tabela com o cadastro de motivos de ocorrências.

      - name: stg_regioes
        description: Tabela com o cadastro das regiões de destino.