version: 2

sources:
  - name: staging
    description: Dados vindos do source, com pequenos tratamentos..


    tables:
      - name: base_dados
        description: Tabela com os registros das vendas.
        
      - name: custos_mensais
        description: Tabela com os registros dos custos.

      - name: cadastro_veiculos
        description: Tabela com o cadastro dos veículos da empresa. 

      - name: motivos_ocorrencias
        description: Tabela com o cadastro de motivos de ocorrências.

      - name: regioes
        description: Tabela com o cadastro das regiões de destino.